# Generated by Django 3.1.7 on 2021-03-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szafka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='szafka',
            name='plyta',
            field=models.IntegerField(default=False),
        ),
    ]
