# Generated by Django 3.1.7 on 2021-03-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szafka', '0002_szafka_plyta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szafka',
            name='glebokosc',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='szafka',
            name='szerokosc',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='szafka',
            name='wysokosc',
            field=models.IntegerField(default=False),
        ),
    ]
